controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login:
    path: /login
    #  controller: lexik_jwt_authentication.controller.token::getToken
    #  methods: [ POST ]